# Generated by Django 5.2.17 on 2026-10-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantphoto',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='city',
            field=models.CharField(default='São Paulo, SP', max_length=200),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='job',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
