# Generated by Django 5.2.17 on 2026-10-04 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_participantphoto_position_participantprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoutfitphoto',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantphoto',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('consent', 'Consentimento'), ('choice', 'Opções')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
