# Generated by Django 5.2.17 on 2026-10-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_eventoutfitphoto_captured_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='purpose',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
