# Generated by Django 5.2.17 on 2026-10-08 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_participantprofile_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('options', models.JSONField(default=list)),
                ('multiple', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='topic_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
