# Generated by Django 5.2.17 on 2026-10-04 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventadministrator_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='event',
            name='location_interval_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Presencial'), ('HYBRID', 'Híbrido')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='opening_origin',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automática')], max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='radius_m',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendado'), ('OPEN', 'Aberto'), ('RUNNING', 'Em andamento'), ('PAUSED', 'Pausado'), ('CLOSED', 'Encerrado'), ('ARCHIVED', 'Arquivado')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='tolerance_m',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='eventadministrator',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventadministrator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventadministrator',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
