# Generated by Django 5.2.17 on 2026-10-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_operational_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pass_payment_instructions',
            field=models.TextField(blank=True),
        ),
    ]
