# Generated by Django 5.2.17 on 2026-10-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
