# Generated by Django 5.2.17 on 2026-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_eventparticipant_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='location_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='presence',
            field=models.CharField(choices=[('UNKNOWN', 'Não confirmada'), ('PRESENT', 'Presente'), ('OUTSIDE', 'Temporariamente fora'), ('DISTANT', 'Fora do limite')], default='UNKNOWN', max_length=12),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registration_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Cadastro incompleto'), ('PENDING', 'Aguardando ativação'), ('ACTIVE', 'Ativo'), ('INACTIVE', 'Desativado')], default='INCOMPLETE', max_length=12),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='social_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
