# Generated by Django 5.2.17 on 2026-10-04 19:43

from django.db import migrations, models

def snapshot_names(apps,schema_editor):
    Pass=apps.get_model('passes','ParticipantPass')
    for item in Pass.objects.select_related('offer__pass_type').filter(offer_name=''):
        Pass.objects.filter(pk=item.pk).update(offer_name=item.offer.pass_type.name)


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_existing_pass_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpass',
            name='offer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(snapshot_names,migrations.RunPython.noop),
    ]
