# Generated by Django 5.2.17 on 2026-10-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_eventsuspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcase',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baixa'), (1, 'Normal'), (2, 'Alta')], default=1),
        ),
    ]
