# Generated by Django 5.2.17 on 2026-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recurring_reported',
            field=models.BooleanField(default=False),
        ),
    ]
