# Generated by Django 5.2.17 on 2026-10-03 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass')], max_length=4)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions_sent', to='participants.eventparticipant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions_received', to='participants.eventparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass')], max_length=4)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='interactions.interaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('participant', 'target'), name='interactions_interaction_unique'),
        ),
    ]
