# Generated by Django 5.2.17 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_created_by_alter_report_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_unfounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportevidence',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
