# Generated by Django 5.2.17 on 2026-10-03 22:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='passes.eventpassoffer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='participants.eventparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.passpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
