# Generated by Django 5.2.17 on 2026-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_contact_email_organization_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Responsável pelo evento'), ('MODERATOR', 'Moderador'), ('OPERATOR', 'Operador')], default='ADMIN', max_length=20),
        ),
    ]
